Revert "[RenderScript] Add CTS correctness tests for L3 BLAS Intrinsic"
error: code too large, moving to native one

This reverts commit a75a13ecd7984f9f80f56d5ec7b96e784ef7d315.

Change-Id: I43a76f5808f9f5bfcca226f8de1b78d295297891