Set LOCAL_SDK_VERSION to 25 in CtsVerifierUSBCompanion
We want the companion app to be able to run successfully
on older versions. Set local sdk version to prevent it
from crashing.

Fixes crash:

01-01 00:07:52.386  7600  7600 E AndroidRuntime:        Suppressed:
java.io.IOException: Failed to open dex files from
/data/app/com.android.cts.verifierusbcompanion-PHLQj4bf-pNf3Sgd5-HlYA==/base.apk
because: Unrecognized version number in
/data/app/com.android.cts.verifierusbcompanion-PHLQj4bf-pNf3Sgd5-HlYA==/base.apk:
0 3 9

Test: passes with api set to P
Bug: 79433866
Change-Id: I88a8a9ff1772ecc9fa15fc9299f90d846aa5e327