fix broken GPL build
cts/tests/tests/os/src/android/os/storage/cts/StorageManagerTest.java:171: error: cannot find symbol
        Assert.assertArrayEquals(expected, actual);
        ^
  symbol:   variable Assert
  location: class StorageManagerTest
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

(cherrypicked from commit 1bd6cae8c8731e97b6f200fcabd6029d11f5ab2d)

Change-Id: I541e5775e0e1c7efb22498d06a18f4401769b635