Revert "[RenderScript] correctness test for L2 BLAS"
error: code too large, moving to native one

This reverts commit 29af6962f802daa5242a222dfd9b7a95cb1e27f7.

Change-Id: I9a2442d1f999340a5cb9cccd240f9131ea26213d